### ISSUE TITLE
Licensing ambiguity

### ISSUE THREAD

**Issue by mrpotes** [ForgeRock/openam-auth-sample#11]
The README for this repo states one type of license (CC variant), but the source code all states a different license (CDDL 1.0).

**Comment by mjang** [comment]
This CC variant is the same one as is used for FR docs, ref https://stash.forgerock.org/projects/OPENIDM/repos/openidm-docs/browse/src/main/docbkx/legal.xml

**Comment by mrpotes** [comment]
Yep, but the code shouldn't then be stating CDDL. There is no docs in this repo (apart from one paragraph of README)

**Comment by mjang** [comment]
We have CC licensing for our docs -- and CDDL licensing for our code in our projects, throughout. I'm not sure I understand the problem.

**Comment by mrpotes** [comment]
The licenses are not compatible - the readme is expressing that the contents of the repo can be used in a non-commercial, non-derivative way, but the source code states it is licensed using a different license, that *does* permit commercial and derivative works.

**Comment by markcraig** [comment]
My understanding is that ForgeRock has full copyright, in which case we can make the license CDDL.

**Comment by markcraig** [comment]
Fixed with <https://github.com/ForgeRock/openam-auth-sample/commit/ef6c38bf50b581a5f8ca9090edc8493bb8c2e5ce>
